### ISSUE TITLE
Error while dumping dialogs

### ISSUE THREAD

**Issue by thomastesla-acdc** [ngalayko/vk_dump#3]
I wrote python instead of python3 because python3 wasn't recognized and while dumping a dialog gets 
File "C:<...>\vk_dump-master\func.py, line 69, in dump_dialogs 
check = dialog['chat_id'] 
KeyError: 'chat_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "vk_dump.py", line 45, in <module>
    func.dump_dialogs(vk_api, user_id)
  File "C:\Users\User\Desktop\vk_dump-master\func.py", line 87, in dump_dialogs
    dump_dialog_history(vk_api, id_to_dump, is_multichat, newpath)
  File "C:\Users\User\Desktop\vk_dump-master\func.py", line 152, in dump_dialog_history
    + message['body'] + '\n')
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\encodings\cp1251.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 47-48: character maps to <undefined>

**Comment by ngalaiko** [comment]
You are probably running python 2.x, and it causes the problem.
Make sure you are using puthon version 3.x.
